(SIMP-10399) Change all `master` configs to `server`
simp/pupmod-simp-pupmod pull request #159
Opened 2021-08-17 18:35 UTC by trevor-vaughan

* Fixed
  - Change all instances of pupmod::master adding items to the `master` section to
    use `server` instead
  - Update pupmod::conf to automatically switch `master` to `server`
  - Automatically remove items from the puppet config in the `master` section that
    are set in the `server` section

SIMP-10399 #close

2021-08-19 14:14 UTC, lnemsick-simp commented
When I use this PR with the latest SIMP components in the simp-core acceptance test and Puppet 6.24.0, it still does not solve the problem:
[puppet.conf.bad_sections.txt](https://github.com/simp/pupmod-simp-pupmod/files/7014937/puppet.conf.bad_sections.txt)
What are we missing? Are the old puppetlabs modules a problem?

2021-08-19 14:20 UTC, lnemsick-simp requested changes
This PR does not solve the problem and should not close the bug ticket.

2021-08-24 13:03 UTC, trevor-vaughan commented
@lnemsick-simp This PR goes as far as we can. Those two settings are controlled by the `puppetdb` module and [have not been modified](https://github.com/puppetlabs/puppetlabs-puppetdb/blob/main/manifests/master/storeconfigs.pp#L12).

2021-08-24 13:07 UTC, trevor-vaughan commented
Filed [a bug](https://tickets.puppetlabs.com/browse/MODULES-11172)

2021-08-24 13:48 UTC, lnemsick-simp commented
- What are the ramifications of mixed configuration?
- Should this module have an option to use `master` or `server` to avoid the mixed configuration until the `puppetdb` module is fixed?

2021-08-24 17:41 UTC, trevor-vaughan commented
@lnemsick-simp Works fine. Everything falls back to `master`

2021-08-24 19:27 UTC, lnemsick-simp approved these changes

2021-08-24 19:54 UTC, merged